[build]
  command = "pnpm build"
  publish = "dist"
  functions = "functions"  # Only needed if using Netlify Functions

[build.environment]
  NODE_VERSION = "20"  # Recommended LTS version
  NPM_FLAGS = "--version"  # Ensures npm is available
  PNPM_VERSION = "8"  # Lock pnpm version

[context.production.environment]
  ASTRO_STANDARD_MODE = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/videos/product-video-poster.webp"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*.webp"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*.svg"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/_image"
  to = "/404.html"
  status = 404

# Edge Functions (optional)
[[edge_functions]]
  path = "/api/*"
  function = "api"